delete from system.consolidation_config;  

INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application', 'application', 'application', 'Applications that have the status = “to-be-transferred”.', 'status_code = ''to-be-transferred'' and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''application.application'')', false, 1, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.service', 'application', 'service', 'Every service that belongs to the application being selected for transfer.', 'application_id in (select id from consolidation.application) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''application.service'')', false, 2, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('transaction.transaction', 'transaction', 'transaction', 'Every record that references a record in consolidation.service.', 'from_service_id in (select id from consolidation.service) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''transaction.transaction'')', false, 3, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('transaction.transaction_source', 'transaction', 'transaction_source', 'Every record that references a record in consolidation.transaction.', 'transaction_id in (select id from consolidation.transaction) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''transaction.transaction_source'')', false, 4, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.cadastre_object_target', 'cadastre', 'cadastre_object_target', 'Every record that references a record in consolidation.transaction.', 'transaction_id in (select id from consolidation.transaction) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.cadastre_object_target'')', false, 5, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.cadastre_object_node_target', 'cadastre', 'cadastre_object_node_target', 'Every record that references a record in consolidation.transaction.', 'transaction_id in (select id from consolidation.transaction) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.cadastre_object_node_target'')', false, 6, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application_uses_source', 'application', 'application_uses_source', 'Every record that belongs to the application being selected for transfer.', 'application_id in (select id from consolidation.application) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''application.application_uses_source'')', false, 7, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application_property', 'application', 'application_property', 'Every record that belongs to the application being selected for transfer.', 'application_id in (select id from consolidation.application) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''application.application_property'')', false, 8, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application_spatial_unit', 'application', 'application_spatial_unit', 'Every record that belongs to the application being selected for transfer.', 'application_id in (select id from consolidation.application) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''application.application_spatial_unit'')', false, 9, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit', 'cadastre', 'spatial_unit', 'Every record that is referenced from application_spatial_unit or that is a targeted from a service already extracted or created from a service already extracted in consolidation schema.', '(id in (select spatial_unit_id from consolidation.application_spatial_unit) 
or id in (select id from cadastre.cadastre_object where transaction_id in (select id from consolidation.transaction))
or id in (select cadastre_object_id from consolidation.cadastre_object_target)
) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.spatial_unit'')', false, 10, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit_in_group', 'cadastre', 'spatial_unit_in_group', 'Every record that references a record in consolidation.spatial_unit', 'spatial_unit_id in (select id from consolidation.spatial_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.spatial_unit_in_group'')', false, 11, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.cadastre_object', 'cadastre', 'cadastre_object', 'Every record that is also in consolidation.spatial_unit', 'id in (select id from consolidation.spatial_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.cadastre_object'')', false, 12, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit_address', 'cadastre', 'spatial_unit_address', 'Every record that references a record in consolidation.spatial_unit.', 'spatial_unit_id in (select id from consolidation.spatial_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.spatial_unit_address'')', false, 13, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_value_area', 'cadastre', 'spatial_value_area', 'Every record that references a record in consolidation.spatial_unit.', 'spatial_unit_id in (select id from consolidation.spatial_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.spatial_value_area'')', false, 14, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.survey_point', 'cadastre', 'survey_point', 'Every record that references a record in consolidation.transaction.', 'transaction_id in (select id from consolidation.transaction) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.survey_point'')', false, 15, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.legal_space_utility_network', 'cadastre', 'legal_space_utility_network', 'Every record that is also in consolidation.spatial_unit', 'id in (select id from consolidation.spatial_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''cadastre.legal_space_utility_network'')', false, 16, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit_group', 'cadastre', 'spatial_unit_group', 'Every record  different from STATE and LGA', 'hierarchy_level >2', true, 17, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_contains_spatial_unit', 'administrative', 'ba_unit_contains_spatial_unit', 'Every record that references a record in consolidation.cadastre_object.', 'spatial_unit_id in (select id from consolidation.cadastre_object) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.ba_unit_contains_spatial_unit'')', false, 18, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.source_historic', 'source', 'source_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.source)', true, 43, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_target', 'administrative', 'ba_unit_target', 'Every record that references a record in consolidation.transaction.', 'transaction_id in (select id from consolidation.transaction) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.ba_unit_target'')', false, 19, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit', 'administrative', 'ba_unit', 'Every record that is referenced by consolidation.application_property or consolidation.ba_unit_contains_spatial_unit or consolidation.ba_unit_target.', '(id in (select ba_unit_id from consolidation.application_property) or id in (select ba_unit_id from consolidation.ba_unit_contains_spatial_unit) or id in (select ba_unit_id from consolidation.ba_unit_target)) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.ba_unit'')', false, 20, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.required_relationship_baunit', 'administrative', 'required_relationship_baunit', 'Every record that references a record in consolidation.ba_unit.', 'from_ba_unit_id in (select id from consolidation.ba_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.required_relationship_baunit'')', false, 21, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_area', 'administrative', 'ba_unit_area', 'Every record that references a record in consolidation.ba_unit.', 'ba_unit_id in (select id from consolidation.ba_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.ba_unit_area'')', false, 22, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_as_party', 'administrative', 'ba_unit_as_party', 'Every record that references a record in consolidation.ba_unit.', 'ba_unit_id in (select id from consolidation.ba_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.ba_unit_as_party'')', false, 23, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.source_describes_ba_unit', 'administrative', 'source_describes_ba_unit', 'Every record that references a record in consolidation.ba_unit.', 'ba_unit_id in (select id from consolidation.ba_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.source_describes_ba_unit'')', false, 24, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.rrr', 'administrative', 'rrr', 'Every record that references a record in consolidation.ba_unit.', 'ba_unit_id in (select id from consolidation.ba_unit) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.rrr'')', false, 25, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.rrr_share', 'administrative', 'rrr_share', 'Every record that references a record in consolidation.rrr.', 'rrr_id in (select id from consolidation.rrr) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.rrr_share'')', false, 26, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.party_for_rrr', 'administrative', 'party_for_rrr', 'Every record that references a record in consolidation.rrr.', 'rrr_id in (select id from consolidation.rrr) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.party_for_rrr'')', false, 27, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.lease_condition_for_rrr', 'administrative', 'lease_condition_for_rrr', 'Every record that references a record in consolidation.rrr.', 'rrr_id in (select id from consolidation.rrr) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.lease_condition_for_rrr'')', false, 28, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.mortgage_isbased_in_rrr', 'administrative', 'mortgage_isbased_in_rrr', 'Every record that references a record in consolidation.rrr.', 'rrr_id in (select id from consolidation.rrr) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.mortgage_isbased_in_rrr'')', false, 29, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.source_describes_rrr', 'administrative', 'source_describes_rrr', 'Every record that references a record in consolidation.rrr.', 'rrr_id in (select id from consolidation.rrr) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.source_describes_rrr'')', false, 30, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.notation', 'administrative', 'notation', 'Every record that references a record in consolidation.ba_unit or consolidation.rrr or consolidation.transaction.', '(ba_unit_id in (select id from consolidation.ba_unit) or rrr_id in (select id from consolidation.rrr) or transaction_id in (select id from consolidation.transaction)) and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''administrative.notation'')', false, 31, true);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.source', 'source', 'source', 'Every source that is referenced from the consolidation.application_uses_source 
or consolidation.transaction_source
or source that references consolidation.transaction or source that is referenced from consolidation.source_describes_ba_unit or source that is referenced from consolidation.source_describes_rrr.', 'id in (select source_id from consolidation.application_uses_source)
or id in (select source_id from consolidation.transaction_source)
or transaction_id in (select id from consolidation.transaction)
or id in (select source_id from consolidation.source_describes_ba_unit)
or id in (select source_id from consolidation.source_describes_rrr) ', true, 32, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.power_of_attorney', 'source', 'power_of_attorney', 'Every record that is also in consolidation.source.', 'id in (select id from consolidation.source)', true, 33, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.spatial_source', 'source', 'spatial_source', 'Every record that is also in consolidation.source.', 'id in (select id from consolidation.source)', true, 34, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.spatial_source_measurement', 'source', 'spatial_source_measurement', 'Every record that references a record in consolidation.spatial_source.', 'spatial_source_id in (select id from consolidation.spatial_source)', true, 35, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.archive', 'source', 'archive', 'Every record that is referenced from a record in consolidation.source.', 'id in (select archive_id from consolidation.source) ', true, 36, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('document.document', 'document', 'document', 'Every record that is referenced by consolidation.source.', 'id in (select ext_archive_id from consolidation.source)', true, 37, false);
--INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.party', 'party', 'party', 'Every record that is referenced by consolidation.application or consolidation.ba_unit_as_party or consolidation.party_for_rrr.', 'id in (select agent_id from consolidation.application) or id in (select contact_person_id from consolidation.application) or id in (select agent_id from consolidation.application) or id in (select party_id from consolidation.party_for_rrr) or id in (select party_id from consolidation.ba_unit_as_party)', true, 38, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) 
VALUES ('party.party', 'party', 'party', 'Every record that is referenced by consolidation.application or consolidation.ba_unit_as_party or consolidation.party_for_rrr.', 
'id in (select agent_id from consolidation.application) or
 id in (select contact_person_id from consolidation.application) 
or 
id in (select agent_id from consolidation.application) or 
id in (select party_id from consolidation.party_for_rrr) or
 id in (select party_id from consolidation.ba_unit_as_party) or
 (id in (select party_id from party.party_role where (type_code = ''demOfficer'' or type_code=''recOfficer'')
  and rowidentifier not in (select rowidentifier from system.extracted_rows where table_name=''party.party''))
 )', true, 38, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.group_party', 'party', 'group_party', 'Every record that is also in consolidation.party.', 'id in (select id from consolidation.party)', true, 39, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.party_member', 'party', 'party_member', 'Every record that references a record in consolidation.party.', 'party_id in (select id from consolidation.party)', true, 40, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.party_role', 'party', 'party_role', 'Every record that references a record in consolidation.party.', 'party_id in (select id from consolidation.party)', true, 41, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('address.address', 'address', 'address', 'Every record that is referenced by consolidation.party or consolidation.spatial_unit_address.', 'id in (select address_id from consolidation.party) or id in (select address_id from consolidation.spatial_unit_address)', true, 42, false);

---historic
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.survey_point_historic', 'cadastre', 'survey_point_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.survey_point)', false, 44, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_value_area_historic', 'cadastre', 'spatial_value_area_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.spatial_value_area)', false, 45, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit_address_historic', 'cadastre', 'spatial_unit_address_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.spatial_unit_address)', false, 46, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.spatial_source_measurement_historic', 'source', 'spatial_source_measurement_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.spatial_source_measurement)', false, 47, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.spatial_source_historic', 'source', 'spatial_source_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.spatial_source)', true, 48, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.source_describes_rrr_historic', 'administrative', 'source_describes_rrr_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.source_describes_rrr)', false, 49, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.rrr_historic', 'administrative', 'rrr_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.rrr)', false, 50, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.required_relationship_baunit_historic', 'administrative', 'required_relationship_baunit_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.required_relationship_baunit)', false, 51, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.power_of_attorney_historic', 'source', 'power_of_attorney_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.power_of_attorney)', true, 52, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.party_role_historic', 'party', 'party_role_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.party_role)', true, 53, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.party_member_historic', 'party', 'party_member_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.party_member)', true, 54, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.party_for_rrr_historic', 'administrative', 'party_for_rrr_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.party_for_rrr)', false, 55, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.legal_space_utility_network_historic', 'cadastre', 'legal_space_utility_network_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.legal_space_utility_network)', false, 56, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.group_party_historic', 'party', 'group_party_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.group_party)', true, 57, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.lease_condition_for_rrr_historic', 'administrative', 'lease_condition_for_rrr_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.lease_condition_for_rrr)', false, 58, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.cadastre_object_historic', 'cadastre', 'cadastre_object_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.cadastre_object)', false, 59, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_target_historic', 'administrative', 'ba_unit_target_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.ba_unit_target)', false, 60, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_contains_spatial_unit_historic', 'administrative', 'ba_unit_contains_spatial_unit_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.ba_unit_contains_spatial_unit)', false, 61, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_area_historic', 'administrative', 'ba_unit_area_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.ba_unit_area)', false, 62, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('source.archive_historic', 'source', 'archive_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.archive)', true, 63, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application_property_historic', 'application', 'application_property_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.application_property)', false, 64, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application_historic', 'application', 'application_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.application)', false, 65, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('transaction.transaction_source_historic', 'transaction', 'transaction_source_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.transaction_source)', false, 66, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('transaction.transaction_historic', 'transaction', 'transaction_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.transaction)', false, 67, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit_in_group_historic', 'cadastre', 'spatial_unit_in_group_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.spatial_unit_in_group)', false, 68, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit_group_historic', 'cadastre', 'spatial_unit_group_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.spatial_unit_group)', false, 69, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.spatial_unit_historic', 'cadastre', 'spatial_unit_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.spatial_unit)', false, 70, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.source_describes_ba_unit_historic', 'administrative', 'source_describes_ba_unit_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.source_describes_ba_unit)', false, 71, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.service_historic', 'application', 'service_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.service)', false, 72, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.rrr_share_historic', 'administrative', 'rrr_share_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.rrr_share)', false, 73, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('party.party_historic', 'party', 'party_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.party)', true, 74, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.notation_historic', 'administrative', 'notation_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.notation)', false, 75, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.mortgage_isbased_in_rrr_historic', 'administrative', 'mortgage_isbased_in_rrr_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.mortgage_isbased_in_rrr)', false, 76, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('document.document_historic', 'document', 'document_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.document)', true, 77, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.cadastre_object_target_historic', 'cadastre', 'cadastre_object_target_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.cadastre_object_target)', false, 78, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('cadastre.cadastre_object_node_target_historic', 'cadastre', 'cadastre_object_node_target_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.cadastre_object_node_target)', false, 79, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('administrative.ba_unit_historic', 'administrative', 'ba_unit_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.ba_unit)', false, 80, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application_uses_source_historic', 'application', 'application_uses_source_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.application_uses_source)', false, 81, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('application.application_spatial_unit_historic', 'application', 'application_spatial_unit_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.application_spatial_unit)', false, 82, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES ('address.address_historic', 'address', 'address_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.address)', false, 83, false);

---SR  

INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.dispute', 'administrative', 'dispute', 'Every dispute that references an application being selected for transfer.', 'application_id in (select id from consolidation.application)', false, 84, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.dispute_historic', 'administrative', 'dispute_historic', 'record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.dispute)', false, 85, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.dispute_comments', 'administrative', 'dispute_comments', 'Every comments that references a dispute being selected for transfer.', 'dispute_nr in (select nr from consolidation.dispute)', false, 86, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.dispute_comments_historic', 'administrative', 'dispute_comments_historic', 'record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.dispute_comments)', false, 87, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.dispute_party', 'administrative', 'dispute_party', 'Every dispute party that references a dispute being selected for transfer.', 'dispute_nr in (select nr from consolidation.dispute)', false, 88, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.dispute_party_historic', 'administrative', 'dispute_party_historic', 'record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.dispute_party)', false, 89, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.source_describes_dispute', 'administrative', 'source_describes_dispute', 'Every record that references a record in consolidation.dispute.', 'dispute_id in (select id from consolidation.dispute)', false, 90, false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('administrative.source_describes_dispute_historic', 'administrative', 'source_describes_dispute_historic', 'Every record that references a record in consolidation.dispute.', 'rowidentifier in (select rowidentifier from consolidation.source_describes_dispute)', false, 91, false);

INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('cadastre.sr_work_unit', 'cadastre', 'sr_work_unit', 'Every record',  NULL , true, 92, false);

INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('party.source_describes_party', 'party', 'source_describes_party', 'Every record that references a record in consolidation.party.', 'party_id in (select id from consolidation.party)', false, 93,  false);
INSERT INTO system.consolidation_config (id, schema_name, table_name, condition_description, condition_sql, remove_before_insert, order_of_execution, log_in_extracted_rows) VALUES  ('party.source_describes_party_historic', 'party', 'source_describes_party_historic', 'Every record that references a record in the main table in consolidation schema.', 'rowidentifier in (select rowidentifier from consolidation.source_describes_party)', false, 94, false);
